ramp_segment:
  a: [0, 120]
  b: [400, 0]
  radius: 1
  elasticity: 0.5
  friction: 0.5

horizontal_segment:
  a: [400, 0]
  b: [640, 0]
  radius: 1
  elasticity: 0.5
  friction: 0.5

ball:
  mass: 1.0
  moment: 10.0
  position: [50, 150]
  elasticity: 0.5
  friction: 0.5
  radius: 20.0

box:
  size: [50, 50]
  friction: 0.9
  elasticity: 0.05
